### ISSUE TITLE
Request to Disable or Customize the New Border Feature

### ISSUE THREAD

**Issue by zhimbura** [Chaintech-Network/QRKitComposeMultiplatform#17]
I noticed that in the latest version, a border has been added. It would be very useful if it could be disabled or if a custom drawing function could be provided, as if the application has its own design, it needs to have its own borders.

![image](https://github.com/user-attachments/assets/6dae5131-5f91-4ffb-ae31-2dffc5379430)

![image](https://github.com/user-attachments/assets/19d129a7-7706-4278-b7ce-4c4d5591a196)

**Comment by ctn-mobile-innovation** [comment]
Please check latest version, it's added @zhimbura
