### ISSUE TITLE
Compose Image Loader update dependency version

### ISSUE THREAD

**Issue by santyas** [Chaintech-Network/QRKitComposeMultiplatform#19]
Hey guys!

I've created an [issue](https://github.com/qdsfdhvh/compose-imageloader/issues/636) into compose-imageloader repo thinking there is an error there but I found that dependency is used here (not updated version).

[compose-imageloader Releases](https://github.com/qdsfdhvh/compose-imageloader/releases)

Could you check if is it OK to update it with the last version?
Thank you so much :)

**Comment by mayur-ctn** [comment]
@santyas Check version 3.0.3

**Comment by santyas** [comment]
3.0.0 is the ktor last version

**Comment by santyas** [comment]
There are no more errors at build time once qrkit is updated :) Thank you!
