### ISSUE TITLE
Barcode scanner does not work on iPhones

### ISSUE THREAD

**Issue by KunnievShamil** [Chaintech-Network/QRKitComposeMultiplatform#4]
I can’t say about all iPhones, since I only tested it on the iPhone XR, do you have this problem?

**Comment by jishinhv** [comment]
Yes, have seen it not work on IPhone XR most times but some runs via xcode, when lucky, we've gotten it to work 25% of the times after playing around with the configs and versions, never consistently though. 

This has been hampering our full adoption as we have it working for android pretty much every time. We're looking at building this separately inhouse if its going to take longer for the CTN team to resolve.

**Comment by jishinhv** [comment]
@ctn-mobile-innovation do we have a fix for this also in the upcoming release? This is on non-triple camera phones.

**Comment by ctn-mobile-innovation** [comment]
Please check in new version and let us know!

**Comment by ctn-mobile-innovation** [comment]
Fixed in v 1.0.8
