### ISSUE TITLE
Missing source code

### ISSUE THREAD

**Issue by dzwicker** [Chaintech-Network/QRKitComposeMultiplatform#6]
In the Maven POM the artefacts are released under the MIT. So, where is the source code repo?

**Comment by ctn-mobile-innovation** [comment]
@dzwicker it's open-source, with little effort you can view the code, but yes unlike many other repos we have not provided direct code to prevent misuse.

**Comment by dzwicker** [comment]
Please read the MIT. I ask for the code. Please provide me with a URL to fetch the source code. And please explain the term 'misuse'. I believe this hole repo is just a marketing thing. I will open a case in GitHub for all your repos. And see https://github.com/Chaintech-Network/QRKitComposeMultiplatform/issues/13

**Comment by yuroyami** [comment]
@ctn-mobile-innovation May you explain what "misuse" you're talking about ? Open-source is open-source. The open-source licenses protect you from this so-called misuse. If you're not willing to contribute to the open-source with OPEN-SOURCE code, you might as well start selling your libraries and with different licenses.
