### ISSUE TITLE
Barcodes

### ISSUE THREAD

**Issue by andiosdev** [Chaintech-Network/QRKitComposeMultiplatform#9]
Hi, not that it is an issue, but this is only limited to QR codes and does not include barcodes?

**Comment by ctn-mobile-innovation** [comment]
@andiosdev it will work for some type of barcode, but we will update supported types and format in read.me

**Comment by andiosdev** [comment]
> @andiosdev it will work for some type of barcode, but we will update supported types and format in read.me

I see. I tried with bar code 128 and it does nothing.

**Comment by andiosdev** [comment]
> @andiosdev it will work for some type of barcode, but we will update supported types and format in read.me

Can the view be adjusted? Instead of square for QR, rectangle for barcode.

**Comment by ctn-mobile-innovation** [comment]
@andiosdev It's added in latest version Please check and let us know!
